pipeline {
    agent any

    environment {
        // Terraform wants these env-vars
        TF_IN_AUTOMATION = 'true'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Lint') {
            steps {
                sh 'make lint'
            }
        }

        stage('Plan') {
            steps {
                withCredentials([string(credentialsId: 'proxmox-token', variable: 'PM_SECRET')]) {
                    withEnv([
                        "TF_VAR_pm_api_token_id=root@pam!terraform1",
                        "TF_VAR_pm_api_token_secret=${PM_SECRET}"
                    ]) {
                        sh 'make plan'
                    }
                }
            }
        }

        stage('Apply') {
            when {
              expression {
                // This works in both single and multibranch jobs,
                // as long as you tell Git to checkout "main".
                return env.GIT_BRANCH?.endsWith('main') || env.BRANCH_NAME == 'main'
              }
            }
            steps {
              withCredentials([string(credentialsId: 'proxmox-token', variable: 'PM_SECRET')]) {
                withEnv([
                  "TF_VAR_pm_api_token_id=root@pam!terraform1",
                  "TF_VAR_pm_api_token_secret=${PM_SECRET}"
                ]) {
                  sh 'make apply'
                }
              }
            }
          }
    }
}